BOT_TOKEN: 
  - MTAzMjg5MTcwODIzMDM0ODgyMQ.G2S73h.IjGhjjQr7d_Xf_NFNzsXS93IXSdwhcMxWgN7oE
  - 
CHANNEL_ID: 
  - 958520731652730900
  - 87751xxxxxxxxxxxxxx
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 10
DEL_AFTER: 
REPOST_LAST_CHAT: 100
